# Generated by Django 5.1 on 2025-02-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='division',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='roll_no',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
