# Generated by Django 5.1 on 2025-02-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetail', '0003_user_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='division',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='roll_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
