# Generated by Django 5.1 on 2025-04-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetail', '0004_alter_user_division_alter_user_roll_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=255)),
                ('roll_no', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=20)),
                ('division', models.CharField(max_length=5)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('academic_year', models.CharField(max_length=9)),
                ('was_promoted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
