# Generated by Django 5.1 on 2025-04-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Placement', '0002_companyannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='academic_year',
            field=models.CharField(default='2024-25', max_length=9),
            preserve_default=False,
        ),
    ]
