# Generated by Django 5.1 on 2025-02-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_id', models.CharField(max_length=12, unique=True)),
                ('subject_id', models.CharField(max_length=12)),
                ('text_content', models.TextField()),
                ('attached_docs', models.BooleanField(default=False)),
                ('document_paths', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.CharField(max_length=12, unique=True)),
                ('subject_id', models.CharField(max_length=12)),
                ('document_paths', models.JSONField()),
                ('text_content', models.TextField()),
                ('all_submits', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_id', models.CharField(max_length=12, unique=True)),
                ('subject_id', models.CharField(max_length=12)),
                ('code', models.CharField(max_length=6)),
                ('attendance', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=12, unique=True)),
                ('announcement_id', models.CharField(max_length=12)),
                ('student_id', models.CharField(max_length=12)),
                ('comment_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=12)),
                ('subject_id', models.CharField(max_length=12, unique=True)),
                ('subject_name', models.CharField(max_length=255)),
                ('college_year', models.CharField(choices=[('first_year', 'First Year'), ('second_year', 'Second Year'), ('third_year', 'Third Year'), ('fourth_year', 'Fourth Year'), ('fifth_year', 'Fifth Year')], max_length=20)),
            ],
        ),
    ]
