# Generated by Django 5.1 on 2025-02-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassRoom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='class_division',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
