# Generated by Django 5.1 on 2025-02-18 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClassRoom', '0003_announcement_created_at_assignment_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='student_id',
            new_name='user_id',
        ),
    ]
