# Generated by Django 5.1 on 2025-02-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassRoom', '0004_rename_student_id_comment_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkedAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_id', models.CharField(max_length=12)),
                ('student_id', models.CharField(max_length=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='attendance',
        ),
    ]
