# Generated by Django 5.1 on 2025-03-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassRoom', '0006_assignment_attached_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='deadline_date',
            field=models.DateField(default='2025-03-25'),
            preserve_default=False,
        ),
    ]
