# Generated by Django 5.1 on 2025-03-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassRoom', '0007_assignment_deadline_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='deadline_date',
            field=models.DateTimeField(),
        ),
    ]
