# Generated by Django 5.1 on 2025-03-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassRoom', '0008_alter_assignment_deadline_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='teacher_id',
            field=models.CharField(default='T8917844452', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='teacher_id',
            field=models.CharField(default='T8917844452', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='teacher_id',
            field=models.CharField(default='T8917844452', max_length=12),
            preserve_default=False,
        ),
    ]
