# Generated by Django 5.1 on 2025-03-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassRoom', '0010_submittedassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedassignment',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
