# Generated by Django 5.1 on 2025-03-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassRoom', '0011_submittedassignment_text_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='class_division',
            field=models.CharField(default='A', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='college_year',
            field=models.CharField(default='fifth_year', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='class_division',
            field=models.CharField(default='A', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='college_year',
            field=models.CharField(default='fifth_year', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='class_division',
            field=models.CharField(default='A', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='college_year',
            field=models.CharField(default='fifth_year', max_length=20),
            preserve_default=False,
        ),
    ]
