# Generated by Django 5.1 on 2025-04-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassRoom', '0012_announcement_class_division_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=9, unique=True)),
                ('is_current', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='academic_year',
            field=models.CharField(default='2024-25', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='academic_year',
            field=models.CharField(default='2024-25', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='academic_year',
            field=models.CharField(default='2024-25', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='academic_year',
            field=models.CharField(default='2024-25', max_length=9),
            preserve_default=False,
        ),
    ]
