# Generated by Django 5.1 on 2025-07-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassRoom', '0013_academicyear_announcement_academic_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTrackEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(max_length=12, unique=True)),
                ('teacher_id', models.CharField(max_length=12)),
                ('date', models.DateField()),
                ('activity_type', models.CharField(max_length=50)),
                ('subject_id', models.CharField(blank=True, max_length=12, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('description', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('academic_year', models.CharField(max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
